### PR TITLE
Refactor and forward client codes.

### PR DESCRIPTION
**Pull request by cristianvasquez**
Changes:

Refactor
Forward client codes.

### CODE REVIEW

**Comment by ludovicm67** [comment]
I did some changes so that we can load this handler as a regular Trifid middleware using the new configuration system.
It still needs some fixes, because some tests are now failing.

**Comment by ludovicm67** [comment]
This is how you can try this handler by yourself:

```sh
mkdir trifid-tests # create a dedicated directory
cd trifid-tests # go in that directory
npm init # init a new npm project (just hit "Enter" until the end)
npm install trifid-core # install the trifid-core package
```

Then use your favorite text editor to add the `start` script like this in the `scripts` section of the `package.json` file:

```json
{
  "scripts": {
    "start": "trifid-core",
    "test": "echo \"Error: no test specified\" && exit 1"
  }
}
```

Create a `config.yaml` file with the following content:

```yaml
middlewares:
  sparql-handler:
    module: file:trifid-handler-sparql/index.js
    config:
      endpointUrl: https://path/to/some/particular/sparql/endpoint
```

and clone this repo, install dependencies, and go in the `trifid-tests` directory back:

```sh
git clone git@github.com:zazuko/trifid-handler-sparql.git
cd trifid-handler-sparql
git checkout develop
npm install
cd ..
```

Then you should be able to run the instance:

```sh
npm run start
```

And this is how to run tests:

```sh
npm run test
```

**Comment by ludovicm67** [comment]
Regarding the tests that are failing, it looks like it only does one query, so everything that checks for a second one is failing.

Can someone with more historical background on this middleware help a bit on debugging this?
Maybe @bergos?

**Comment by ludovicm67** [comment]
Tests are now passing well again 🎉

**Comment by cristianvasquez** [comment]
Hi @ludovicm67 ,

Using your guideline, I've just tried to test this with `trifid-core": "^2.0.0-alpha.4`. The middleware expects the value of `IRI` that apparently comes in the request.

https://github.com/zazuko/trifid-handler-sparql/blob/7ca7af25473c721bd2dc3bf722bb3fccb7060bc2/index.js#L102

 What is the middleware/component that needs to the added to the config, so this value is set?

**Comment by bergos** [comment]
[absolute-url](https://www.npmjs.com/package/absolute-url) will be loaded by Trifid. The middleware should expect it to be loaded and use the `req.absoluteUrl()` method directly.

**Review by bergos — APPROVED** [review]

**Pull request merged**
